# -*- coding: utf-8 -*-
"""
verify_figures.py
=================
For every Chapter-4 figure, verify that:
  1. The source npz files exist with the correct shape and node count.
  2. The npz freq arrays match the expected frequencies.
  3. Node counts cross-check against the xlsx and text-cited values.
  4. For field figures, the npz shape is [8, N] (4 freq × 2 samples).
  5. For depth-line figures, the selection pipeline sources are traceable.

This is structural verification — checking provenance and data integrity, not
pixel-level figure reproduction (which would require matplotlib version pinning
and font matching). The generated figures are the output of scripts in
Validation_Scripts/; this verifier confirms the input data is present and valid.
"""
import numpy as np
import paper_values as PV
import data_sources as DS
import depthline_recompute as DL


class Finding:
    __slots__ = ("kind", "ident", "expected", "actual", "ok", "source", "note")

    def __init__(self, kind, ident, expected, actual, ok, source, note=""):
        self.kind = kind
        self.ident = ident
        self.expected = expected
        self.actual = actual
        self.ok = ok
        self.source = source
        self.note = note

    def as_dict(self):
        return dict(kind=self.kind, id=self.ident, expected=self.expected,
                    actual=self.actual, ok=self.ok, source=self.source, note=self.note)


def verify_figures():
    findings = []
    for label, (kind, refs) in PV.FIGURES.items():
        if kind == "field":
            _verify_field_figure(label, refs, findings)
        elif kind == "depthline":
            _verify_depthline_figure(label, refs, findings)
        elif kind == "split":
            _verify_split_figure(label, refs, findings)
        elif kind == "runtime":
            _verify_runtime_figure(label, refs, findings)
    return findings


def _verify_field_figure(label, case_nos, findings):
    """Each field figure renders TL grids from per-case npz. Verify npz exists,
    shape [8,N], freq set, and N matches xlsx/text when cited."""
    for no in case_nos:
        section, case_dir = PV.CASE_MAP[no]
        z, rel = DS.load_npz(section, case_dir)
        if z is None:
            findings.append(Finding("figure", f"{label}:No{no}", "npz", "missing",
                                    False, "-", "source npz not found"))
            continue
        # Check shape: [8,N] for multi-freq (4×2), [2,N] for single-freq (1×2)
        pred = z["pred_tl"]
        fem = z["fem_tl"]
        freqs = z["freq"]
        exp_nrow = 8 if len(freqs) == 8 else 2
        ok_shape = (pred.ndim == 2 and pred.shape[0] == exp_nrow and
                    fem.shape == pred.shape)
        N = pred.shape[1] if pred.ndim == 2 else 0
        findings.append(Finding(
            "figure", f"{label}:No{no}:shape", f"[{exp_nrow},N]",
            list(pred.shape) if pred.ndim == 2 else "wrong ndim",
            ok_shape, rel, f"N={N}"))
        # Check freq set
        freqs = z["freq"]
        freq_set = sorted(set(int(round(float(f))) for f in freqs))
        exp_freqs = [25, 50, 75, 100] if len(freqs) == 8 else [100]
        ok_freq = freq_set == exp_freqs
        findings.append(Finding(
            "figure", f"{label}:No{no}:freq", exp_freqs, freq_set,
            ok_freq, rel))
        # Cross-check node count
        if no in PV.NODE_COUNTS:
            exp_n = PV.NODE_COUNTS[no]
            ok_n = (N == exp_n)
            findings.append(Finding(
                "figure", f"{label}:No{no}:nodecount", exp_n, N, ok_n, rel,
                f"text-cited N={exp_n}"))


def _verify_depthline_figure(label, groups, findings):
    """Depth-line figures are generated by advantage_depth_line.py from ensemble
    npz. Verify each member npz exists, shape [8,N], and the selection pipeline
    can run."""
    for group in groups:
        section, force_y, members = DL.GROUP_MEMBERS[group]
        for case_dir, lbl in members:
            z, rel = DS.load_npz(section, case_dir)
            if z is None:
                findings.append(Finding("figure", f"{label}:{group}:{lbl}", "npz",
                                        "missing", False, "-"))
                continue
            pred = z["pred_tl"]
            ok = pred.ndim == 2 and pred.shape[0] == 8
            findings.append(Finding(
                "figure", f"{label}:{group}:{lbl}:shape", "[8,N]",
                list(pred.shape) if pred.ndim == 2 else "wrong", ok, rel))
        # Verify the selection pipeline runs (already tested in verify_tables, but
        # record a figure-specific check).
        try:
            got, yline, srcs = DL.recompute_group(DS.load_npz, group)
            ok = len(got) == 4
        except Exception as e:
            got, yline, srcs = None, None, []
            ok = False
        findings.append(Finding(
            "figure", f"{label}:{group}:selection",
            "4 freqs", f"{len(got) if got else 0} freqs", ok,
            "; ".join(srcs) if srcs else "-", f"force_y={force_y}"))


def _verify_split_figure(label, case_nos, findings):
    """Source-position split figure (fig:gen-split) uses coordinates from the
    dataset manifest and split labels from train_test_split.pth. Verify the npz
    source_pos array exists and has 8 entries (4 freq × 2 samples)."""
    for no in case_nos:
        section, case_dir = PV.CASE_MAP[no]
        z, rel = DS.load_npz(section, case_dir)
        if z is None:
            findings.append(Finding("figure", f"{label}:No{no}", "npz", "missing",
                                    False, "-"))
            continue
        sp = z["source_pos"]
        ok = sp.ndim == 2 and sp.shape == (8, 2)
        findings.append(Finding(
            "figure", f"{label}:No{no}:source_pos", "[8,2]",
            list(sp.shape) if sp.ndim == 2 else "wrong", ok, rel))


def _verify_runtime_figure(label, case_nos, findings):
    """Runtime figure (fig:perf) plots data from the performance xlsx. Verify the
    xlsx rows exist and node counts match the npz."""
    runtime, scale, src = DS.load_perf()
    rt = {r["case"]: r for r in runtime}
    sc = {r["case"]: r for r in scale}
    for no in case_nos:
        if no in (43, 44):
            row = rt.get(no)
            ok = row is not None
            findings.append(Finding("figure", f"{label}:No{no}:runtime",
                                    "present", "ok" if ok else "missing", ok, src))
        else:
            row = sc.get(no)
            ok = row is not None
            findings.append(Finding("figure", f"{label}:No{no}:scale",
                                    "present", "ok" if ok else "missing", ok, src))
        # Cross-check N
        section, case_dir = PV.CASE_MAP[no]
        z, rel = DS.load_npz(section, case_dir)
        if z is not None and row is not None:
            N_npz = z["x_coords"].shape[0]
            N_xlsx = row.get("N")
            ok_n = (N_npz == N_xlsx)
            findings.append(Finding(
                "figure", f"{label}:No{no}:N_crosscheck", N_xlsx, N_npz, ok_n, rel))


if __name__ == "__main__":
    import io, sys
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
    allf = verify_figures()
    bad = [f for f in allf if not f.ok]
    print(f"figures: {len(allf)} checks, {len(allf)-len(bad)} pass, {len(bad)} fail")
    for f in bad[:40]:
        print("  FAIL", f.ident, "exp", f.expected, "got", f.actual, f.note)
